dist: xenial

language: c

matrix:
  include:
    # linux GCC
    - os: linux
      name: Linux GCC
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - libsdl2-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - liblua5.3-dev
      env:
        - MATRIX_EVAL="CC=gcc-7"

    # OSX CLANG
    - os: osx
      osx_image: xcode9.4
      name: OSX Clang
      addons:
        homebrew:
          packages:
            - sdl2
            - lua@5.3
          update: true

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - ctest
