version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing SDL2 and Lua 5.3
          command: 'apt-get update && apt-get install -y libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev liblua5.3-dev'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Release Configuration
          command: 'cmake -DCMAKE_BUILD_TYPE=Release'
      - run:
          name: Build
          command: 'cmake --build'